
name: Java CI with Gradle

on: workflow_dispatch
    
jobs:
   tests:
    name: Bild enviroment and testing
    runs-on: windows-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
        cache: gradle
   # - name: Set up Chrome browser
    #  uses: browser-actions/setup-chrome@v1
  
    #- name: Install Chrome
    #  uses: browser-actions/setup-chrome@latest
      
    #- name: Make gradlew executable
    #  run: chmod +x ./gradlew  
    
   # - name: Validate Gradle wrapper
    #  uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
   # - name: Build with Gradle
   #   uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
    #  with:
    #    arguments: build --stacktrace
    
    - name: Run tests with Gradle
      run: ./gradlew test

  
   generate_report:
      name: II. Generate & Deploy Allure report
      runs-on: ubuntu-latest
      if: always()
      needs: [ tests ]
      steps:
        - name: Get Allure history
          uses: actions/checkout@v3
          if: always()
          continue-on-error: true
          with:
           ref: gh-pages
           path: gh-pages
       
        - name: Test marketplace action
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
            allure_results: allure-results
            allure_history: allure-history
            allure_report: allure-report
            gh_pages: gh-pages
            #ref: gh-pages
            #path: gh-pages
            keep_reports: 30
         
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PUBLISH_BRANCH: gh-pages
           PUBLISH_DIR: ./allure-history 
           commit_message: ${{ github.event.head_commit.message }}
      
        
      
