
name: Java CI with Gradle

on: workflow_dispatch
    
jobs:
   tests:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
   # - name: Install Chrome
    #  uses: browser-actions/setup-chrome@latest
        
   # - name: Validate Gradle wrapper
   #   uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      
   # - name: Make gradlew executable
   #   run: chmod +x ./gradlew
      
  #  - name: Build with Gradle
   #   uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
   #   with:
   #       arguments:
    #          build
    #          --stacktrace  
    
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
    - name: Build with Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      with:
        arguments: build --debag
  
   generate_report:
      name: II. Generate & Deploy Allure report
      runs-on: ubuntu-latest
      if: always()
      needs: [ tests ]
      steps:
        - name: Get Allure history
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
           ref: gh-pages
           path: gh-pages
       
        - name: Test marketplace action
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
            allure_results: allure-results
            allure_history: allure-history
            allure_report: allure-report
            gh_pages: gh-pages
            ref: gh-pages
            path: gh-pages
            keep_reports: 30
         
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PUBLISH_BRANCH: gh-pages
           PUBLISH_DIR: allure-history 
      
        
      
